### ISSUE TITLE
chagossupport.org.uk link is dead

### ISSUE THREAD

**Issue by lukechilds** [greenkeeperio/website#25]
https://github.com/greenkeeperio/website/blob/source/app/partials/_footer.ejs#L23

Maybe change to https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/

Also, thanks for bringing this to my attention, I had no idea 👍

**Comment by janl** [comment]
Their Twitter is still active, might be a glitch with the website registration, I’ve asked for clarification: https://twitter.com/janl/status/761179395872661504

**Comment by janl** [comment]
https://twitter.com/ChagosUK/status/761231087674744833

**Comment by lukechilds** [comment]
lololol

**Comment by janl** [comment]
the site is back up: https://twitter.com/ChagosUK/status/761262345289072640
